FROM dunglas/frankenphp:1.8-php8.4-alpine

WORKDIR /srv

RUN apk add --no-cache autoconf build-base \
    && pecl install redis \
    && docker-php-ext-enable redis

COPY ./cmd/api.php /srv/public/index.php

ENV WORKER_COUNT=16

ENV FRANKENPHP_CONFIG="worker /srv/public/index.php ${WORKER_COUNT}"
ENV SERVER_NAME=":80"