x-service-templates:
  api: &api
    build:
      context: .
      dockerfile: Dockerfile.api
    image: leoralph/rinha-de-backend-2025-api
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "90M"

services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30M"

  redis:
    image: redis:latest
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60M"

  payment-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: leoralph/rinha-de-backend-2025-worker
    environment:
      - WORKER_TYPE=payment
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "60M"

  health-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: leoralph/rinha-de-backend-2025-worker
    environment:
      - WORKER_TYPE=health
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20M"

  api01:
    <<: *api

  api02:
    <<: *api

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
