FROM dunglas/frankenphp:1.8-php8.4-alpine

RUN apk add --no-cache autoconf build-base \
    && pecl install redis \
    && docker-php-ext-enable redis

WORKDIR /srv

COPY ./cmd/api.php /srv/public/index.php

ENV FRANKENPHP_CONFIG="worker /srv/public/index.php 5"
ENV SERVER_NAME=":80"