FROM dunglas/frankenphp:1.8-php8.4-alpine

WORKDIR /srv

RUN apk add --no-cache autoconf build-base \
    && pecl install redis \
    && docker-php-ext-enable redis

COPY ./cmd/worker.php /srv/worker.php

HEALTHCHECK NONE

ENTRYPOINT ["php", "/srv/worker.php"]