FROM dunglas/frankenphp:1.8-php8.4-alpine

RUN apk add --no-cache autoconf build-base \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pcntl

WORKDIR /srv

COPY ./cmd/*-worker.php /srv

HEALTHCHECK NONE

ENV WORKER_TYPE=payment

ENTRYPOINT ["sh", "-c", "php /srv/${WORKER_TYPE}-worker.php"]
